# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: "docker-compose"
    directories:
      - "HPNas/Misc/"
      - "HPNas/Networking/"
      - "HPNas/Storage/"
      - "PC/"
      - "PiHome/Apps/"
      - "PiHome/Finances/"
      - "PiHome/IOT/"
      - "PiHome/Networking/"
      - "PiHome/Security/"
      - "PiLab/Networking/"
      - "PiWeb/Networking/"
      - "PrusaPrint/Networking/"
      - "Utils/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope